### ISSUE TITLE
Pandoc citations

### ISSUE THREAD

**Issue by jgm** [leeper/htlatex-example#1]
Pandoc dev here :).  I noticed a couple things in your comparison that could be improved.

To get bibliographic references working in pandoc, you need to tell pandoc to use the `pandoc-citeproc` filter (included with default pandoc binary packages).

```
pandoc manuscript.tex -o manuscript-pandoc.docx --filter pandoc-citeproc
```

Optionally, the `--csl` option may be used to specify a CSL stylesheet that more closely matches apsa-leeper.bst than the default chicago-author-date.csl.

Another thing you may want to mention is that pandoc converts the equation into a native Word equation object, while htlatex just inserts an image with the equation as typeset by LaTeX (which doesn't match the font of the Word document, and can't be edited).

**Comment by leeper** [comment]
Awesome. This is really helpful. I'll update with this info.

**Comment by leeper** [comment]
Also, pandoc is generally really awesome and I use it all the time (for md -> everything conversion).
